In [1]:
import pandas as pd

movies = pd.read_csv('movies.csv')

print(movies.head())

          title   genres                              overview
0      Avengers   Action            Superheroes save the world
1      Iron Man   Action  A billionaire builds a powerful suit
2          Thor   Action         God of thunder protects earth
3       Titanic  Romance        A love story on a sinking ship
4  The Notebook  Romance       Romantic drama about two lovers

In [2]:
movies.info()
movies.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     7 non-null      object
 1   genres    7 non-null      object
 2   overview  7 non-null      object
dtypes: object(3)
memory usage: 300.0+ bytes

           title  genres                    overview
count          7       7                           7
unique         7       3                           7
top     Avengers  Action  Superheroes save the world
freq           1       3                           1

In [3]:
movies["tags"] = movies["genres"] + " " + movies["overview"] 

movies.head()

,title,genres,overview,tags
0,Avengers,Action,Superheroes save the world,Action Superheroes save the world
1,Iron Man,Action,A billionaire builds a powerful suit,Action A billionaire builds a powerful suit
2,Thor,Action,God of thunder protects earth,Action God of thunder protects earth
3,Titanic,Romance,A love story on a sinking ship,Romance A love story on a sinking ship
4,The Notebook,Romance,Romantic drama about two lovers,Romance Romantic drama about two lovers

In [4]:
movies["tags"] = movies["tags"].apply(lambda x: x.lower())

In [5]:
movies = movies[['title','tags']]

movies.head()

          title                                         tags
0      Avengers            action superheroes save the world
1      Iron Man  action a billionaire builds a powerful suit
2          Thor         action god of thunder protects earth
3       Titanic       romance a love story on a sinking ship
4  The Notebook      romance romantic drama about two lovers

In [ ]:
#Vectorization 
# Text -> Numbers
#Vocabulary

In [6]:
from sklearn.feature_extraction.text import CountVectorizer 
cv = CountVectorizer(max_features=5000, stop_words="english")

vectors = cv.fit_transform(movies["tags"]).toarray()

In [8]:
vectors
vectors.shape

(7, 29)

In [9]:
cv.get_feature_names_out()

array(['action', 'adventures', 'bean', 'billionaire', 'builds', 'comedy',
       'drama', 'earth', 'finds', 'funny', 'god', 'love', 'lovers',
       'magical', 'man', 'mask', 'mr', 'powerful', 'protects', 'romance',
       'romantic', 'save', 'ship', 'sinking', 'story', 'suit',
       'superheroes', 'thunder', 'world'], dtype=object)

In [10]:
#Cosine Similarity 

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)
similarity.shape

(7, 7)

In [11]:
similarity[0]

array([1.       , 0.2236068, 0.2236068, 0.       , 0.       , 0.       ,
       0.       ])

In [12]:
movies.head()

          title                                         tags
0      Avengers            action superheroes save the world
1      Iron Man  action a billionaire builds a powerful suit
2          Thor         action god of thunder protects earth
3       Titanic       romance a love story on a sinking ship
4  The Notebook      romance romantic drama about two lovers

In [13]:
movies[movies["title"] == "Avengers"].index[0]

0

In [14]:
similarity = cosine_similarity(vectors)

In [15]:
similarity[0]

array([1.       , 0.2236068, 0.2236068, 0.       , 0.       , 0.       ,
       0.       ])

In [20]:
movie_list = list(enumerate(similarity[0]))

In [21]:
sorted(movie_list, reverse=True, key=lambda x: x[1])

[(0, 1.0),
 (1, 0.22360679774997896),
 (2, 0.22360679774997896),
 (3, 0.0),
 (4, 0.0),
 (5, 0.0),
 (6, 0.0)]

In [22]:
def recommend(movie):

    index = movies[movies["title"] == movie].index[0]

    distances = similarity[index]

    movie_list = sorted(list(enumerate(distances)),
                        reverse=True,
                        key=lambda x: x[1])[1:6]

    for i in movie_list:
        print(movies.iloc[i[0]].title)

In [24]:
recommend("Avengers")

Iron Man
Thor
Titanic
The Notebook
The Mask